# Generated by Django 5.2.5 on 2025-09-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Inventory', 'Inventory'), ('Non-Inventory', 'Non-Inventory'), ('Service', 'Service'), ('Bundle', 'Bundle')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sell_checkbox', models.BooleanField(default=False)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable', models.BooleanField(default=False)),
                ('purchase_checkbox', models.BooleanField(default=False)),
                ('is_bundle', models.BooleanField(default=False)),
                ('display_bundle_contents', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'Expenses'}, on_delete=django.db.models.deletion.CASCADE, related_name='expense_products', to='accounts.account')),
                ('income_account', models.ForeignKey(limit_choices_to={'account_type': 'Income'}, on_delete=django.db.models.deletion.CASCADE, related_name='income_products', to='accounts.account')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sowaf.newsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='inventory.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bundle', to='inventory.product')),
            ],
        ),
    ]
