# Generated by Django 5.2.5 on 2025-09-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'Cost of sales'}, on_delete=django.db.models.deletion.CASCADE, related_name='expense_products', to='accounts.account'),
        ),
    ]
