# Generated by Django 5.2.5 on 2025-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_expense_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='purchase_description',
        ),
        migrations.AddField(
            model_name='product',
            name='sales_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
