# Generated by Django 5.2.5 on 2025-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_description_product_purchase_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
