# Generated by Django 5.2.4 on 2025-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=128)),
                ("confirm_user", models.CharField(max_length=128)),
            ],
        ),
    ]
