# Generated by Django 5.2.5 on 2025-09-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_journalentry_journalline'),
        ('sales', '0006_alter_invoiceitem_discount_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.newinvoice'),
        ),
    ]
