# Generated by Django 5.2.5 on 2025-09-11 10:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='line_total',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='newinvoice',
            old_name='tax',
            new_name='total_vat',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='billable',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='income_account',
            field=models.ForeignKey(limit_choices_to={'type': 'Income'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
