# Generated by Django 5.2.5 on 2025-09-11 10:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_line_total_invoiceitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_num',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
