# Generated by Django 5.2.5 on 2025-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoiceitem_discount_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='income_account',
        ),
    ]
