# Generated by Django 5.2.5 on 2025-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_invoiceitem_income_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newinvoice',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='newinvoice',
            old_name='invoice_due',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='newinvoice',
            old_name='item_details',
            new_name='lclass',
        ),
        migrations.RenameField(
            model_name='newinvoice',
            old_name='po_number',
            new_name='po_num',
        ),
        migrations.RenameField(
            model_name='newinvoice',
            old_name='discount',
            new_name='shipping_fee',
        ),
        migrations.RenameField(
            model_name='newinvoice',
            old_name='shipping',
            new_name='total_discount',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='newinvoice',
            name='location',
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
