# Generated by Django 5.2.5 on 2025-09-11 12:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_newinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_num',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
