# Generated by Django 5.2.5 on 2025-09-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_purchase_price_and_more'),
        ('sales', '0007_payment_paymentinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newinvoice',
            name='lclass',
        ),
        migrations.AddField(
            model_name='newinvoice',
            name='class_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
            preserve_default=False,
        ),
    ]
