# Generated by Django 5.2.5 on 2025-09-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_newinvoice_lclass_newinvoice_class_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newinvoice',
            name='class_field',
        ),
    ]
