# Generated by Django 5.2.5 on 2025-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_newinvoice_class_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='newinvoice',
            name='lclass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
