# Generated by Django 5.2.5 on 2025-10-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_newinvoice_lclass_newinvoice_class_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinvoice',
            old_name='amount_applied',
            new_name='amount_paid',
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='sales.payment'),
        ),
    ]
