# Generated by Django 5.2.5 on 2025-10-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_parent'),
        ('sales', '0012_rename_amount_applied_paymentinvoice_amount_paid_and_more'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sowaf.newcustomer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_applied', to='sales.newinvoice'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_invoices', to='sales.payment'),
        ),
    ]
