# Generated by Django 5.2.5 on 2025-10-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_parent'),
        ('sales', '0013_alter_payment_customer_alter_payment_deposit_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='deposit_to',
            field=models.ForeignKey(limit_choices_to={'account_type__in': ['Bank', 'Cash and Cash Equivalents']}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='accounts.account'),
        ),
    ]
