# Generated by Django 5.2.5 on 2025-10-14 04:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salesreceipt_salesreceiptline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
