# Generated by Django 5.2.5 on 2025-10-23 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journalentry_expense_alter_columnpreference_user'),
        ('expenses', '0002_columnpreference'),
        ('inventory', '0006_alter_product_purchase_price_and_more'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_address', models.CharField(blank=True, max_length=255)),
                ('terms', models.CharField(blank=True, max_length=50)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('bill_no', models.CharField(db_index=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bill_attachments/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.journalentry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillCategoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billable', models.BooleanField(default=False)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('clazz', models.CharField(blank=True, max_length=120)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_lines', to='expenses.bill')),
            ],
        ),
        migrations.CreateModel(
            name='BillItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billable', models.BooleanField(default=False)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('clazz', models.CharField(blank=True, max_length=120)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='expenses.bill')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_no'], name='expenses_bi_bill_no_2eb706_idx'),
        ),
    ]
