# Generated by Django 5.2.5 on 2025-10-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_bill_billcategoryline_billitemline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitemline',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillCategoryLine',
        ),
        migrations.DeleteModel(
            name='BillItemLine',
        ),
    ]
