# Generated by Django 5.2.5 on 2025-10-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_bill_billcategoryline_billitemline'),
        ('inventory', '0006_alter_product_purchase_price_and_more'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billcategoryline',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='customer_project',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='customer_project',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='product_service',
        ),
        migrations.AddField(
            model_name='billcategoryline',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
        ),
        migrations.AddField(
            model_name='billcategoryline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer'),
        ),
        migrations.AddField(
            model_name='billitemline',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
        ),
        migrations.AddField(
            model_name='billitemline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer'),
        ),
        migrations.AddField(
            model_name='billitemline',
            name='product',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
    ]
