# Generated by Django 5.2.5 on 2025-10-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_billcategoryline_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitemline',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='billcategoryline',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='billitemline',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillCategoryLine',
        ),
        migrations.DeleteModel(
            name='BillItemLine',
        ),
    ]
