# Generated by Django 5.2.5 on 2025-10-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journalentry_expense_alter_columnpreference_user'),
        ('expenses', '0008_bill_billcategoryline_billitemline'),
        ('inventory', '0006_alter_product_purchase_price_and_more'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newsupplier'),
        ),
        migrations.AlterField(
            model_name='billcategoryline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='billcategoryline',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
        ),
        migrations.AlterField(
            model_name='billcategoryline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer'),
        ),
        migrations.AlterField(
            model_name='billitemline',
            name='class_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass'),
        ),
        migrations.AlterField(
            model_name='billitemline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer'),
        ),
        migrations.AlterField(
            model_name='billitemline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
