# Generated by Django 5.2.5 on 2025-10-31 12:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journalentry_expense_alter_columnpreference_user'),
        ('expenses', '0009_alter_bill_supplier_alter_billcategoryline_category_and_more'),
        ('inventory', '0006_alter_product_purchase_price_and_more'),
        ('sowaf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(blank=True, max_length=255)),
                ('mailing_address', models.CharField(blank=True, max_length=255)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('cheque_no', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('memo', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_payments', to='accounts.account')),
                ('payee_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newsupplier')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChequeCategoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_lines', to='expenses.cheque')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_billable', models.BooleanField(default=False)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='expenses.cheque')),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pclass')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sowaf.newcustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
